import React from 'react';
import Navigation from "../components/Navigation";
import Logo from "../components/Logo"
const Home = () => {
    return (
        <div>
            <Logo />
            <Navigation />
            <h1>ACCUEIL</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde sapiente natus beatae fuga incidunt, deleniti minus quas! Eum illum sint laudantium impedit, natus quos pariatur, unde eveniet voluptatibus hic necessitatibus!
            Exercitationem consectetur suscipit similique deleniti aperiam iure facilis neque illo animi, ex accusamus dicta consequuntur ducimus necessitatibus incidunt, magnam, quos ad hic. Dolore quod quas provident facilis sunt deserunt quae.
            Quos esse dignissimos vero suscipit dolorum ratione nesciunt provident quae eveniet expedita fugiat, iste libero debitis mollitia earum excepturi vitae sed aspernatur molestiae qui pariatur quia eos! Voluptatibus, culpa iure?
            Nisi nostrum possimus cupiditate, atque soluta nobis tempora mollitia voluptates doloribus error, blanditiis iste. Praesentium soluta nulla dolores cupiditate, recusandae quia nihil ut deleniti alias ex aspernatur sunt vero aut.
            Aut voluptatem necessitatibus quaerat pariatur consequatur aperiam reiciendis eum esse debitis corporis? Ratione obcaecati voluptatibus incidunt alias aspernatur? Accusantium dolor veniam eos, temporibus aut corporis voluptatem quasi totam numquam nemo!
            Veritatis officia, eaque natus enim dolore impedit debitis quas non unde, explicabo sit vitae ea! Nam autem doloremque quasi asperiores necessitatibus sapiente, dolore explicabo nulla numquam consequatur, cupiditate odit distinctio.
            Necessitatibus quod magnam ullam distinctio expedita consequuntur numquam culpa accusamus commodi suscipit corrupti quas voluptates ratione natus vel ipsam dolore quos, voluptatibus molestiae fuga iure exercitationem repellat assumenda provident. Ipsa.
            Officia dignissimos quo atque magni ullam enim voluptatum animi sint veritatis dicta, explicabo, quis fugiat ut, sunt in nostrum incidunt deserunt at reprehenderit. Voluptas, mollitia saepe officiis quod dicta eaque.
            Itaque accusantium officia aspernatur quam, nisi doloribus quos. Suscipit voluptate nesciunt quam illo veniam. Blanditiis dolor obcaecati eum vel architecto sed libero rerum, velit cum repellendus pariatur, similique et reiciendis.
            Accusantium cupiditate libero aperiam repudiandae suscipit, explicabo aut eaque quam saepe, fuga perferendis. Quod voluptatum obcaecati quos voluptates expedita odio labore illum sit, recusandae perspiciatis reiciendis repellat porro numquam laborum?
            Aperiam dolore necessitatibus magnam. Dignissimos quisquam incidunt in repellendus temporibus nihil, expedita provident magni? Velit assumenda perspiciatis dolore nam asperiores atque a enim fugit ullam deleniti voluptatum placeat, numquam suscipit.
            Laborum dolore cupiditate dolor, numquam provident vitae possimus deleniti excepturi eius doloribus optio, mollitia, beatae consectetur illum odio libero. Nemo neque ea quis laudantium aut pariatur eum amet corporis sit.
            Soluta neque reiciendis architecto nemo eos doloremque tempora qui ab eveniet fugiat? Cumque perspiciatis aliquid eum quod cum fugit velit nesciunt, repudiandae adipisci temporibus esse aperiam veniam recusandae dolor reiciendis.
            Accusantium, eligendi cumque! Accusantium vel, eaque, culpa debitis saepe molestias ducimus delectus necessitatibus, sit facilis placeat iste magni tempore autem dignissimos recusandae perspiciatis reiciendis explicabo eum? Cumque veritatis quas nihil!
            Quidem doloribus similique tempora aliquam, sequi ducimus, aut mollitia dolore fugit illum explicabo maiores voluptas atque ullam cumque provident at reiciendis perspiciatis tempore asperiores quod id dolorum suscipit! Eveniet, et!
            Fugiat nisi nemo sint deleniti dolorem, quod labore eveniet animi fuga. Repellendus iusto nemo qui accusamus, officiis autem consequatur corrupti delectus, molestiae ut libero natus a est reprehenderit tempore voluptatum.
            Nesciunt consequatur minima aperiam quam, corrupti iste dolore incidunt atque nostrum sunt, quas harum exercitationem voluptate? Tempore non culpa necessitatibus molestiae natus doloremque explicabo asperiores itaque! Inventore accusantium nisi facere!
            Reprehenderit excepturi iusto ducimus error quasi deserunt laboriosam repudiandae, voluptate molestiae, sed est numquam veniam in voluptas blanditiis! Minima illo fugit placeat facere earum molestiae doloribus ullam at quo ipsam?
            Quam dignissimos id adipisci, illum, voluptatibus totam excepturi modi commodi in ipsam, cum error officiis. Error dignissimos natus ipsum temporibus quo aut dolorem cumque pariatur, ducimus sunt iusto repudiandae molestiae!
            Officia eaque asperiores ad ullam fugit repellendus aut in eveniet accusamus quis blanditiis, deserunt doloribus, quos perspiciatis illo ea assumenda magni voluptatem ratione, dolores maiores cumque sunt? Deserunt, veniam soluta.
            Pariatur voluptatem sint esse reprehenderit fugiat ratione magni quis aperiam, unde eos neque earum aliquam perferendis repellendus ipsam animi deleniti officia provident vero. Ipsum officia iure nostrum nobis quidem atque.
            Cupiditate iusto esse quas commodi hic impedit deserunt delectus recusandae! Nihil pariatur sint natus expedita hic officia ratione quibusdam! Unde error reprehenderit magnam cumque animi quidem facere nostrum beatae in!
            Magnam in quidem unde nobis totam nisi pariatur omnis? Modi error repellat molestias doloremque provident distinctio ut numquam reiciendis odio sint nisi laudantium ad esse quod, deserunt blanditiis natus quisquam?
            Eos autem sed ab, nisi quisquam porro quia, ipsam, cumque vero ipsa repellat. Ut, quas ullam! Aut nam cupiditate nostrum laboriosam tempora praesentium optio temporibus est, rem ipsa iure maxime!
            Veniam nihil, suscipit, aspernatur officiis debitis nostrum dolores natus quae aut molestiae labore sunt quaerat repudiandae, quos ullam! Maxime sed repellendus quae. Amet totam facere voluptatum nulla laudantium, officia temporibus!
            Amet ex, eligendi sapiente in autem ipsa. Error ratione repellat rem eos doloremque alias consectetur laborum. Veniam dolores, ab doloremque temporibus soluta fugiat ea dicta! Facere debitis eaque ipsam quo?
            Aliquid aliquam perferendis reiciendis at consectetur quisquam, expedita autem magni suscipit numquam dignissimos. Nemo ducimus molestias blanditiis placeat! Eum atque necessitatibus suscipit, sit illum reprehenderit exercitationem earum hic repudiandae fugit!
            Rerum quaerat nostrum debitis illo et quisquam asperiores minima quos odit magnam temporibus, veritatis molestiae sed mollitia, repellat alias perferendis quasi enim fuga blanditiis iure doloribus rem sapiente accusamus. Ipsam.
            Labore, maxime officiis ab optio totam perspiciatis voluptas nisi fugiat. Dolor, laboriosam corporis! Dicta autem, quasi iusto adipisci ullam corporis quis modi voluptatem laudantium repellat ipsum doloribus sunt provident libero.
            Incidunt, id itaque alias eius dolorum aspernatur et cum quod doloremque illo quisquam autem laudantium nesciunt magni totam, quasi iure maiores accusantium officia atque quo consequuntur ipsum! Enim, alias adipisci!
            Aperiam laudantium optio quam, quae earum aliquam. Commodi voluptas libero unde distinctio adipisci natus illo aliquid, debitis nisi quibusdam, omnis saepe cumque deleniti inventore. Vero at aut odit hic! Architecto?
            Assumenda, alias eligendi porro tenetur quisquam facere consequuntur distinctio sunt explicabo dolores mollitia, adipisci aliquam iste asperiores doloribus aperiam sapiente expedita nihil ducimus impedit ratione delectus quaerat! Nobis, odit animi?
            Eligendi incidunt omnis dolore et dolorum saepe unde est? Maiores iusto, nisi magnam illum dignissimos voluptatum quos maxime ipsa voluptatem at voluptates! Quas amet, fugit animi culpa molestias id repudiandae.
            Accusantium nulla nobis neque repellat, explicabo, recusandae totam placeat, voluptatibus minima at aut earum. Inventore vitae quis similique perferendis, pariatur totam rem debitis, aliquid accusamus accusantium maxime veniam quia nam?
            A similique hic corrupti libero natus, officiis accusantium, nam debitis rem alias possimus quisquam velit cupiditate eligendi nobis iusto laborum magnam cumque ipsum magni vel aspernatur soluta! Suscipit, officia repellat?
            Delectus sequi dolor ut? Laboriosam ut omnis, doloribus cum quod provident facilis expedita placeat quo repudiandae, eos magni vero praesentium non eligendi qui, similique voluptatum consequatur eveniet voluptate aliquid? In.
            Iste explicabo aliquid harum assumenda deserunt molestiae id reprehenderit minima earum, et nihil nemo, quod quas unde dolor necessitatibus, distinctio odio pariatur dolores? Illo perspiciatis soluta odit adipisci sit ad!
            Voluptatem optio quidem at ipsam officiis aspernatur omnis hic similique veritatis tenetur, nulla est totam enim quaerat ducimus animi magni. Aliquam eum praesentium suscipit quos ipsam qui cupiditate doloribus dolorem!
            Necessitatibus tempora id laborum explicabo natus sit earum repudiandae nam, magni aut porro quia numquam iusto soluta odit minus. Porro deserunt nam culpa quas minus corporis molestiae maiores quia eos.
            Alias cum in facere! Atque, molestias ut ducimus delectus laboriosam rerum voluptates laborum quasi hic alias doloremque in vero? Nobis sequi consequatur quidem doloremque quisquam ipsum. Iure vel rem omnis!
            Accusantium nisi quod at ipsum, consectetur minus fugit consequatur officiis, explicabo voluptate beatae! Cum voluptatum enim temporibus sapiente, similique odit esse, fuga fugiat qui error laudantium, doloremque voluptas in. Sequi?
            Facilis illo omnis ab quibusdam perferendis minima error vero inventore suscipit veritatis expedita quidem doloremque, distinctio commodi voluptatum iure! Ullam voluptatibus atque placeat asperiores laudantium, aperiam iusto ut pariatur iure.
            Exercitationem, id delectus! Numquam, cum debitis odit a earum modi dolore iure iste hic nobis quas voluptates eos corporis explicabo dolorem dolores blanditiis voluptatibus repellendus laudantium. Expedita ab temporibus animi!
            Distinctio repellendus optio maiores praesentium accusantium, laudantium quasi cumque iste provident, a, sit assumenda saepe itaque nulla ex dolorum deserunt necessitatibus repellat odit consequatur impedit et eaque dignissimos! Ab, tempore.
            Culpa quod cumque a modi eligendi ea explicabo voluptates. Nesciunt asperiores vitae nam obcaecati voluptatibus perferendis eos ducimus corporis ea, molestiae animi quos magnam in quia omnis exercitationem cupiditate sequi?
            Maiores recusandae consequuntur doloremque ipsam reiciendis officia assumenda fugit nisi obcaecati iusto, harum a, perspiciatis unde! Rerum aperiam omnis ab quos quo quae ex, sapiente ipsam consequuntur enim. Delectus, placeat?
            Fugit, officiis deleniti? Eius cumque laudantium aliquid quas nemo voluptates mollitia obcaecati adipisci ad quis unde, asperiores ipsa sapiente debitis repellendus? Vitae tempora, possimus dignissimos quisquam expedita cupiditate modi asperiores.
            Cupiditate molestiae aperiam velit amet? Incidunt in debitis esse sed ex velit cumque nesciunt exercitationem, aliquid eveniet? Et deleniti, quibusdam ducimus, excepturi sint inventore similique suscipit odit aliquid velit recusandae?
            Alias modi molestias, consectetur velit dolorem incidunt optio quia magnam aperiam consequuntur aliquid ut eum tempora obcaecati! Quis facere repellat voluptatum similique sint placeat, inventore pariatur eligendi architecto ipsam unde.
            Nostrum, doloribus. Mollitia eius delectus animi, quisquam ipsum id sit quaerat quasi sint distinctio eaque tenetur sequi laudantium esse fugiat voluptates officiis? Porro laboriosam veniam ex sapiente veritatis temporibus dignissimos?
            Quidem alias cupiditate provident, nobis corporis, atque eius nostrum adipisci temporibus sequi eos cum! Ea praesentium, vel recusandae numquam doloremque labore optio aperiam eos laborum cumque ad inventore debitis possimus.
            Ipsam aut, maxime dolorum repellat sequi perferendis fugit aliquid quibusdam! Sunt, quibusdam rerum aut explicabo recusandae autem cupiditate placeat eum atque sint quod culpa accusamus laborum voluptatem odio perferendis voluptatum.
            Natus assumenda ab nihil labore quidem optio sapiente eveniet. Inventore libero, minima repellat vero atque facilis nam, tempora nulla assumenda veniam consectetur, quod voluptates unde dolores nostrum architecto voluptas cumque!
            Dicta assumenda, quis minima magni praesentium aperiam aliquid similique perferendis pariatur voluptatum voluptatem autem mollitia iusto beatae earum fugiat omnis modi voluptas quae? Voluptatem earum ex cupiditate, cum mollitia nesciunt?
            Modi, repellat. Pariatur, autem. Explicabo, molestias harum velit laudantium quibusdam mollitia dolor! Impedit minima nihil facilis molestiae esse officia nostrum, doloribus, aut, iusto asperiores mollitia! Sequi aspernatur vitae sunt quos.
            Odit dignissimos, vel officia voluptatum cum consequuntur saepe deserunt accusamus aspernatur! Et porro vitae, magnam ullam sint perspiciatis consectetur, consequatur maxime fuga doloremque natus recusandae laborum esse ipsam nobis incidunt!
            Blanditiis tenetur nemo officiis architecto, id est suscipit nihil excepturi molestiae laudantium eveniet sequi omnis amet minima, consequatur nam sed voluptatibus! Sequi ratione nihil quisquam nesciunt sed natus dicta ipsam.
            Eaque aspernatur ut odit dolorum quaerat minus iste hic fugiat tempore ipsam sit culpa, molestias expedita laborum rem perspiciatis modi dolores, omnis voluptatum commodi quidem vitae itaque deserunt? Nisi, deleniti.
            Sunt laboriosam animi odit sed officiis laudantium tempore iusto consequuntur nihil magnam harum id quis itaque ea totam saepe perspiciatis deleniti similique incidunt voluptatem eligendi, iure aliquid. Reiciendis, expedita beatae?
            Optio quibusdam, ex, magnam repudiandae magni inventore aperiam cumque non quisquam nostrum, temporibus et iusto? Exercitationem est eligendi magni deleniti voluptatibus aliquid pariatur porro quis, nesciunt molestiae reiciendis dignissimos esse!
            Minima dolorem magnam molestiae rerum nemo rem, amet, similique, officia quo vitae labore enim maiores repudiandae est doloribus doloremque mollitia consequatur voluptas hic excepturi earum sequi vero quasi? Illum, maiores.
            Est neque illo nesciunt fugiat. Impedit aut animi numquam omnis. Sapiente cumque error, officia eveniet repellendus consequuntur aspernatur quod architecto animi beatae similique ipsa cupiditate nulla recusandae excepturi magnam sit?
            Cumque, dolorem quis? Nisi magni at ipsa inventore. Est doloribus, consequuntur accusamus odit temporibus rem. Velit inventore porro et aliquam veniam molestias incidunt tempora, praesentium repellendus temporibus, amet sit fuga.
            Excepturi, laudantium. Repudiandae voluptatibus pariatur quis excepturi, doloremque voluptatem. Commodi sunt omnis accusantium, nostrum doloremque repudiandae? Dolore, animi impedit nemo explicabo debitis, ea ipsum corrupti veniam itaque cupiditate iste nostrum.
            Ratione sint itaque temporibus officiis provident dolores voluptatibus alias quisquam officia dignissimos nostrum unde id consequatur amet optio pariatur eum, aliquid dolorum velit soluta praesentium repellendus ducimus! Eius, fugiat aut.
            Non voluptates rerum incidunt necessitatibus fugiat totam repellat fugit harum ab eveniet at quos maxime cupiditate, qui velit tempora nulla expedita quidem dicta praesentium! Ipsum quos unde corrupti deserunt praesentium!
            Tempora, vitae sed iste animi dolore eos harum ipsum impedit placeat qui culpa in suscipit incidunt id? Quo perspiciatis perferendis amet enim error, deleniti repudiandae soluta, atque ullam, vitae ipsa.
            At, autem dolorum praesentium ipsam culpa dolore quidem suscipit laudantium in possimus ea ipsum. Minima inventore repudiandae, culpa veritatis, doloremque consequuntur impedit nemo suscipit optio minus commodi, earum quia aut!
            Saepe, minus quia fugit iure in debitis dolore molestias numquam quae totam quod non similique neque, hic autem eligendi expedita labore? Ea modi, facere sit molestias perspiciatis eos quidem cum.
            Repellendus, aut veritatis? Unde cum voluptatibus deleniti asperiores pariatur ipsam tempore voluptatem voluptates laudantium. Neque cupiditate, ipsum quia cumque amet harum voluptatum laboriosam. Sunt eligendi eius tempore aliquid, deleniti eaque.
            Fugiat tempore dignissimos doloribus aliquid? Cumque dicta sit harum officia architecto, repellendus ipsa inventore unde officiis sequi. Minus ducimus quaerat ipsa ex rem quibusdam corrupti nobis consequatur, reiciendis ipsam numquam.
            Explicabo officiis et suscipit voluptatem rerum fuga cum, praesentium enim totam eaque in earum consequatur vitae molestias neque aliquam exercitationem ab ipsum atque expedita! Expedita aperiam quisquam eum nisi architecto?
            Beatae nesciunt soluta voluptatibus minima accusamus quo suscipit, blanditiis quaerat explicabo eveniet quibusdam dolores quidem repudiandae eligendi amet nisi ex corporis nihil asperiores nulla, harum velit libero fugiat totam. Quos!
            Non, autem. Quis soluta iusto at quia autem placeat repellat dignissimos et eum sunt officia reprehenderit rerum, numquam quibusdam itaque nisi sit voluptas non dicta libero, eaque hic! Quis, iste.
            Architecto optio minima ullam enim eveniet quas expedita, consectetur, at similique recusandae eos qui error assumenda maxime molestias a laboriosam quidem voluptatum impedit consequuntur, quia adipisci eum. A, provident ex?
            Quaerat recusandae sint illum minima cumque rem nemo molestiae! Delectus fugit ipsam ex quam pariatur magnam obcaecati nam aliquam dolorem autem inventore porro, unde ducimus, aspernatur reprehenderit facilis qui vero!
            Ducimus enim perspiciatis doloribus recusandae quasi quo. Sunt maxime, labore neque consequatur debitis, ea aliquid soluta error nisi vero libero officia similique aperiam vel aspernatur non veniam minus! Sunt, nisi.
            Placeat molestiae sapiente natus neque a cupiditate culpa perferendis recusandae. Autem amet cum ab quisquam tempora, suscipit vitae aut accusamus sunt doloremque accusantium eum corporis perspiciatis perferendis magnam itaque. Praesentium?
            Itaque dignissimos rem eum enim praesentium alias! Doloremque, ut aspernatur tenetur, deserunt voluptatem facilis magni similique ducimus et quas suscipit nemo eius voluptatibus sequi, assumenda vero perferendis perspiciatis soluta quaerat!
            Suscipit, ullam similique. Consectetur at animi possimus corporis quis pariatur dolorum labore quod, illo fugit eligendi ipsum soluta quae voluptatum harum porro quos aut facilis. Sapiente doloremque libero quo vel!
            Aperiam ex sint labore repudiandae officiis exercitationem expedita nostrum, natus, iure laborum unde mollitia! Corrupti laboriosam quidem dolores? Dolores minima assumenda sit repellendus dolorem provident nihil architecto quia nulla sequi.
            Temporibus rerum maiores eveniet veritatis assumenda quibusdam, quae culpa impedit molestias. Quia provident quae enim dignissimos sunt, repellat accusamus quis perferendis sit doloribus, doloremque alias a nemo tenetur perspiciatis libero?
            Tempore optio, debitis nulla tenetur eaque quia rem voluptates dolor quos iure, ea sit quis vitae, quas ducimus illo voluptatibus eligendi error quo ratione assumenda. Non, numquam cum. Quia, ea.
            Distinctio nam impedit commodi, labore repellat deleniti modi eligendi quos eaque dignissimos vero id, atque minus itaque sit fuga similique laborum ullam, pariatur ad. Sapiente dolore fuga porro non rerum.
            Libero voluptates animi quod dicta earum neque officia, error consequuntur deleniti voluptatibus, repellat amet? Facilis saepe nobis, ipsum sint itaque atque? Corrupti officiis expedita harum veniam commodi qui ipsa temporibus?
            Pariatur quidem voluptatum labore numquam quae. Minus distinctio, optio dolorem perspiciatis qui sit eum beatae culpa facilis, quod unde velit enim recusandae voluptatem iure dignissimos ad tenetur a quas explicabo!
            Libero obcaecati veritatis quasi distinctio iusto. Illo quam quod, enim reprehenderit voluptatibus officia sint laudantium voluptatum hic sequi ea culpa, recusandae quisquam voluptate explicabo debitis, inventore neque perferendis? Eveniet, veritatis.
            Animi ipsam odit nihil consequuntur commodi reiciendis quo fugiat, laborum aliquid excepturi nesciunt. Ex exercitationem ab, ipsa quis cupiditate et reprehenderit quibusdam reiciendis eveniet. Praesentium laboriosam voluptas atque esse adipisci.
            Debitis ipsum, voluptatem veritatis hic atque nesciunt repellat quibusdam laborum fugit molestias quod ipsam vel maxime impedit deleniti at, consequatur adipisci velit. Quae necessitatibus molestiae, et dicta quidem iste quod!
            Molestiae ut, nostrum officiis illo aut distinctio? Alias, similique. Mollitia, eveniet nemo. Enim totam fugit, nisi ducimus esse tempora, sint, unde suscipit hic at beatae perspiciatis possimus? Quisquam, accusamus non.
            Voluptatem recusandae saepe, veniam velit adipisci laborum quia laudantium veritatis dolor. Eaque ducimus nostrum facilis eos? Officiis quia eveniet ipsam, magnam error esse eius dolorem debitis laboriosam itaque quidem magni.
            Nostrum, praesentium excepturi! Explicabo deserunt temporibus autem ex voluptates quam ab tempore cum, earum, consequatur delectus nisi excepturi debitis officiis. Incidunt vitae necessitatibus ab illo a, quibusdam deleniti eveniet iusto?
            Cupiditate hic accusantium quibusdam unde ab blanditiis autem odio ex laboriosam expedita? Ad eius quaerat alias iste totam sunt blanditiis, exercitationem ut reiciendis, voluptas perferendis ducimus neque reprehenderit ipsum odio!
            Ipsa, enim quia animi sed dolorem culpa quae quo veniam, ipsam facilis impedit modi quam excepturi facere nostrum maiores, ex aliquid vitae. Sequi dolore nulla, saepe et praesentium beatae aliquid.
            Placeat, corrupti? Aliquam aut quos ex consequatur odio magni nemo, ipsum temporibus, nihil eum error pariatur autem repellendus facilis? Aliquam eaque voluptatibus excepturi, minima illum autem dolore et repellat dolor?
            Possimus illo eaque tempore sit natus reprehenderit. Nisi, nostrum obcaecati. Natus, ab? Architecto placeat laudantium necessitatibus nostrum, dolor quis vitae soluta, odio culpa nobis ad beatae est corrupti ducimus voluptatum!
            Impedit aperiam et sapiente est facere! Rerum eos dolore unde quaerat repudiandae pariatur minima, quae vero, fugit delectus magnam praesentium suscipit repellendus voluptatibus reiciendis quo reprehenderit. Odit natus vero obcaecati!
            At ut quos cumque neque eligendi facere voluptas, illo nam similique, inventore pariatur minus. Veritatis nam maxime eligendi reiciendis doloribus illum obcaecati perferendis quas, possimus dolores laborum ipsa, dolor neque.
            Laudantium velit ex, minus quam similique tenetur excepturi quos quisquam soluta ad vero sit alias saepe amet officiis provident, beatae, repudiandae laborum non blanditiis eveniet ratione voluptas! Saepe, odio asperiores?
            Commodi eius obcaecati corporis! Voluptate modi nisi sequi accusantium consequuntur culpa reprehenderit ullam cupiditate est deserunt, harum dolorem doloremque quas, architecto ratione iusto, assumenda optio temporibus. Ab delectus commodi fuga!</p>
        </div>
    );
};

export default Home;